"""LLM client abstraction supporting OpenRouter, Google Gemini, and Mock modes with Tool Calling."""

from __future__ import annotations

import json
import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any

from app.core.config import settings

logger = logging.getLogger(__name__)


@dataclass
class ToolCall:
    """Represents a tool/function call requested by the LLM."""

    id: str
    name: str
    arguments: dict[str, Any]


@dataclass
class LLMTurnResponse:
    """The outcome of an LLM turn: either tool calls to execute or final textual content."""

    content: str | None = None
    tool_calls: list[ToolCall] = field(default_factory=list)


class BaseLLMClient(ABC):
    """Abstract LLM provider client supporting function calling and token streaming."""

    @abstractmethod
    async def generate_turn(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        max_tokens: int = 1024,
    ) -> LLMTurnResponse:
        """Execute a single agent turn with tool support."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        """Yield text chunks as they are generated by the model (final streaming answer)."""
        pass


class OpenRouterLLMClient(BaseLLMClient):
    """OpenRouter / OpenAI-compatible client with tool calling and streaming."""

    def __init__(
        self,
        api_key: str,
        model: str = "google/gemini-3.5-flash",
        base_url: str = "https://openrouter.ai/api/v1",
    ) -> None:
        self.api_key = api_key
        self.model = model
        self.base_url = base_url.rstrip("/")

    def _build_headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.api_key}",
            "HTTP-Referer": "https://yosefteshome.dev",
            "X-Title": "Yosef Portfolio AI Concierge",
            "Content-Type": "application/json",
        }

    async def generate_turn(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        max_tokens: int = 1024,
    ) -> LLMTurnResponse:
        import httpx

        payload_messages = [{"role": "system", "content": system_instruction}]
        for m in messages:
            payload_messages.append(m)

        body: dict[str, Any] = {
            "model": self.model,
            "messages": payload_messages,
            "max_tokens": max_tokens,
            "temperature": 0.2,
            "stream": False,
        }
        if tools:
            body["tools"] = tools
            body["tool_choice"] = "auto"

        async with httpx.AsyncClient(timeout=settings.ai_timeout_seconds) as client:
            response = await client.post(
                f"{self.base_url}/chat/completions",
                headers=self._build_headers(),
                json=body,
            )

            if response.status_code != 200:
                err_text = response.text
                logger.error("OpenRouter API error (%d): %s", response.status_code, err_text)
                return LLMTurnResponse(content="I encountered an error connecting to the AI provider. Please try again.")

            data = response.json()
            choice = data.get("choices", [{}])[0]
            message = choice.get("message", {})

            # Check if LLM requested tool calling
            raw_tool_calls = message.get("tool_calls", [])
            if raw_tool_calls:
                parsed_calls: list[ToolCall] = []
                for tc in raw_tool_calls:
                    fn = tc.get("function", {})
                    fn_name = fn.get("name", "")
                    fn_args_raw = fn.get("arguments", "{}")
                    try:
                        args = json.loads(fn_args_raw) if isinstance(fn_args_raw, str) else fn_args_raw
                    except Exception:
                        args = {}
                    parsed_calls.append(
                        ToolCall(
                            id=tc.get("id", f"call_{fn_name}"),
                            name=fn_name,
                            arguments=args,
                        )
                    )
                return LLMTurnResponse(tool_calls=parsed_calls)

            return LLMTurnResponse(content=message.get("content"))

    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        import httpx

        payload_messages = [{"role": "system", "content": system_instruction}]
        for m in messages:
            payload_messages.append(m)

        body = {
            "model": self.model,
            "messages": payload_messages,
            "max_tokens": max_tokens,
            "temperature": 0.3,
            "stream": True,
        }

        async with httpx.AsyncClient(timeout=settings.ai_timeout_seconds) as client:
            async with client.stream(
                "POST",
                f"{self.base_url}/chat/completions",
                headers=self._build_headers(),
                json=body,
            ) as response:
                if response.status_code != 200:
                    err_text = await response.aread()
                    logger.error("OpenRouter API error (status %d): %s", response.status_code, err_text.decode("utf-8"))
                    yield "I encountered an error connecting to the AI provider. Please try again in a moment."
                    return

                async for line in response.aiter_lines():
                    trimmed = line.strip()
                    if not trimmed or not trimmed.startswith("data:"):
                        continue
                    data_str = trimmed[5:].strip()
                    if data_str == "[DONE]":
                        break
                    try:
                        chunk_json = json.loads(data_str)
                        choices = chunk_json.get("choices", [])
                        if choices:
                            delta = choices[0].get("delta", {})
                            content = delta.get("content")
                            if content:
                                yield content
                    except Exception:
                        continue


class GeminiLLMClient(BaseLLMClient):
    """Google Gemini LLM client using google-genai SDK."""

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash") -> None:
        self.api_key = api_key
        self.model = model
        self._client: Any = None

    def _get_client(self) -> Any:
        if self._client is None:
            from google import genai
            self._client = genai.Client(api_key=self.api_key)
        return self._client

    async def generate_turn(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        max_tokens: int = 1024,
    ) -> LLMTurnResponse:
        # Fallback to streaming content if direct turn is called without tools
        res = ""
        async for chunk in self.generate_stream(
            system_instruction=system_instruction,
            messages=messages,
            max_tokens=max_tokens,
        ):
            res += chunk
        return LLMTurnResponse(content=res)

    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        from google.genai import types
        import anyio

        client = self._get_client()

        contents: list[types.Content] = []
        for msg in messages:
            role = "model" if msg.get("role") in ("assistant", "model") else "user"
            contents.append(
                types.Content(
                    role=role,
                    parts=[types.Part.from_text(text=str(msg.get("content", "")))],
                )
            )

        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            max_output_tokens=max_tokens,
            temperature=0.3,
        )

        def _sync_stream():
            return client.models.generate_content_stream(
                model=self.model,
                contents=contents,
                config=config,
            )

        stream = await anyio.to_thread.run_sync(_sync_stream)
        for chunk in stream:
            if chunk.text:
                yield chunk.text


class MockLLMClient(BaseLLMClient):
    """Deterministic Mock LLM Client with tool-calling simulation for tests & offline dev."""

    def __init__(self, canned_response: str | None = None) -> None:
        self.canned_response = canned_response

    async def generate_turn(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        max_tokens: int = 1024,
    ) -> LLMTurnResponse:
        # Check if the last message is a tool response
        last_msg = messages[-1] if messages else {}
        if last_msg.get("role") == "tool":
            # Tool has returned data — synthesize final text answer
            tool_content = last_msg.get("content", "")
            return LLMTurnResponse(
                content=f"Based on the retrieved information:\n\n{tool_content[:400]}"
            )

        user_query = ""
        for m in reversed(messages):
            if m.get("role") == "user":
                user_query = str(m.get("content", "")).lower()
                break

        # Simulate intelligent tool selection based on intent
        if "postgresql" in user_query or "fastapi" in user_query or "tech" in user_query:
            tech = "PostgreSQL" if "postgresql" in user_query else "FastAPI"
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_tech_1",
                        name="find_projects_by_technology",
                        arguments={"technology": tech, "limit": 4},
                    )
                ]
            )
        elif "christian" in user_query or "booking" in user_query or "agent" in user_query or "rag platform" in user_query:
            slug = (
                "christian-digital-content-platform"
                if "christian" in user_query
                else "intelligent-booking-engine"
                if "booking" in user_query
                else "enterprise-ai-knowledge-platform"
            )
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_proj_1",
                        name="get_project",
                        arguments={"slug": slug},
                    )
                ]
            )
        elif "contact" in user_query or "email" in user_query or "hire" in user_query:
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_contact_1",
                        name="get_contact_information",
                        arguments={},
                    )
                ]
            )
        elif "service" in user_query or "consult" in user_query:
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_service_1",
                        name="get_services",
                        arguments={},
                    )
                ]
            )
        elif "article" in user_query or "blog" in user_query:
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_article_1",
                        name="search_articles",
                        arguments={"query": user_query[:30]},
                    )
                ]
            )
        elif "challenge" in user_query or "decision" in user_query or "architecture" in user_query or "how was" in user_query:
            return LLMTurnResponse(
                tool_calls=[
                    ToolCall(
                        id="call_rag_1",
                        name="search_knowledge_rag",
                        arguments={"query": user_query, "top_k": 4},
                    )
                ]
            )

        # General conversational response without tool
        return LLMTurnResponse(
            content="Hello! I am Yosef's AI portfolio concierge. I can answer questions about his production RAG systems, FastAPI backends, case studies, skills, and availability."
        )

    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, Any]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        import anyio

        turn = await self.generate_turn(
            system_instruction=system_instruction,
            messages=messages,
            max_tokens=max_tokens,
        )
        text = turn.content or "I have processed your request."
        words = text.split(" ")
        for i in range(0, len(words), 3):
            chunk = " ".join(words[i : i + 3]) + (" " if i + 3 < len(words) else "")
            yield chunk
            await anyio.sleep(0.01)


def get_llm_client() -> BaseLLMClient:
    """Factory to retrieve configured LLM client."""
    provider = settings.llm_provider.lower().strip()
    api_key = settings.llm_api_key.strip()

    if provider == "openrouter" and api_key:
        return OpenRouterLLMClient(
            api_key=api_key,
            model=settings.llm_model,
        )

    if provider == "gemini" and api_key:
        return GeminiLLMClient(
            api_key=api_key,
            model=settings.llm_model,
        )

    logger.info("Using MockLLMClient (LLM_API_KEY not configured or in test mode).")
    return MockLLMClient()
