"""LLM client abstraction supporting Google Gemini and fallback / mock modes."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from typing import Any

from app.core.config import settings

logger = logging.getLogger(__name__)


class BaseLLMClient(ABC):
    """Abstract LLM provider client."""

    @abstractmethod
    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, str]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        """Yield text chunks as they are generated by the model."""
        pass


class GeminiLLMClient(BaseLLMClient):
    """Google Gemini LLM client using official google-genai SDK."""

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash") -> None:
        self.api_key = api_key
        self.model = model
        self._client: Any = None

    def _get_client(self) -> Any:
        if self._client is None:
            from google import genai
            self._client = genai.Client(api_key=self.api_key)
        return self._client

    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, str]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        from google.genai import types
        import anyio

        client = self._get_client()

        # Format conversation history for Gemini
        contents: list[types.Content] = []
        for msg in messages:
            role = "model" if msg["role"] == "assistant" else "user"
            contents.append(
                types.Content(
                    role=role,
                    parts=[types.Part.from_text(text=msg["content"])],
                )
            )

        config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            max_output_tokens=max_tokens,
            temperature=0.3,
        )

        def _sync_stream():
            return client.models.generate_content_stream(
                model=self.model,
                contents=contents,
                config=config,
            )

        # Run generator in worker thread to prevent blocking the async event loop
        stream = await anyio.to_thread.run_sync(_sync_stream)
        for chunk in stream:
            if chunk.text:
                yield chunk.text


class MockLLMClient(BaseLLMClient):
    """Mock LLM client for test environments or when no API key is configured."""

    def __init__(self, canned_response: str | None = None) -> None:
        self.canned_response = canned_response

    async def generate_stream(
        self,
        *,
        system_instruction: str,
        messages: list[dict[str, str]],
        max_tokens: int = 1024,
    ) -> AsyncIterator[str]:
        import anyio

        last_user_msg = messages[-1]["content"] if messages else ""
        
        if self.canned_response:
            response = self.canned_response
        elif "project" in last_user_msg.lower():
            response = (
                "Yosef has engineered several production-grade systems including:\n\n"
                "1. **Enterprise AI Knowledge Platform (RAG)**: A high-throughput hybrid retrieval platform using PostgreSQL 17, pgvector, and BM25 ranking.\n"
                "2. **Christian Digital Content Platform**: High-concurrency media streaming architecture with HMAC-signed token security.\n"
                "3. **Intelligent Booking & Scheduling Engine**: Concurrency-isolated transactional scheduling with Redis/Celery.\n"
                "4. **Autonomous AI Agent Workflow Orchestrator**: Multi-step goal execution platform with structured JSON tool calling."
            )
        elif "skill" in last_user_msg.lower() or "tech" in last_user_msg.lower():
            response = (
                "Yosef specializes in **AI Backend & Platform Engineering**. His core stack includes:\n\n"
                "• **Backend**: Python 3.12, FastAPI, SQLAlchemy 2.x, Pydantic v2\n"
                "• **AI / Data**: pgvector, PostgreSQL, RAG architectures, LlamaIndex/LangChain\n"
                "• **Platform**: Docker, Kubernetes, OpenShift, Redis, GitHub Actions CI/CD"
            )
        else:
            response = (
                "Hello! I am Yosef's AI portfolio concierge. I can answer questions about his production RAG systems, "
                "FastAPI backends, engineering case studies, skills, and availability. How can I assist you?"
            )

        # Yield in realistic small chunks
        words = response.split(" ")
        for i in range(0, len(words), 3):
            chunk = " ".join(words[i : i + 3]) + (" " if i + 3 < len(words) else "")
            yield chunk
            await anyio.sleep(0.02)


def get_llm_client() -> BaseLLMClient:
    """Factory to retrieve configured LLM client."""
    if settings.llm_provider == "gemini" and settings.llm_api_key:
        return GeminiLLMClient(api_key=settings.llm_api_key, model=settings.llm_model)
    
    # Fallback to mock when API key not set
    logger.info("Using MockLLMClient (LLM_API_KEY not configured or in test mode).")
    return MockLLMClient()
